# Generated by Django 5.1.4 on 2025-01-12 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_email_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Not valid', regex='^\\+?[1-9]\\d{7,14}')], verbose_name='номер телефона'),
        ),
    ]
